import pyautogui
import asyncio
import aioredis
# import dogtail
# from dogtail.procedural import *
# import dogtail
from dogtail import tree
# virtual directory, virtual filesystem?
async def main():
    # await redis = aioredis.
    redis = await aioredis.create_redis_pool(
    'redis://localhost/')
    p=pyautogui.screenshot()
    print(redis,p)
    # GREAT! GNOME, GTK.
    # OTHERS, CONSIDER XORG, AND DEBUG TOOLS.
# async def main():
#     redis = await aioredis.create_redis_pool('redis://localhost')
#     await redis.set('key', 'string-value')
#     bin_value = await redis.get('key')
#     assert bin_value == b'string-value'
# consider write some docs?
# YES, EDIT BY HANDS.
# gsettings set org.gnome.desktop.interface toolkit-accessibility true
#     str_value = await redis.get('key', encoding='utf-8')
#     assert str_value == 'string-value'

#     redis.close()
#     await redis.wait_closed()

asyncio.run(main())

def nextTool():
    # a=dogtail.utils
    # F=focus.application("zenmap")
    # F=focus.application("Firefox")
    # F=focus.application("nmap") <- false
    F= tree.root.application('code')
    # F= tree.root.application('zenmap')
    # print(F)
    F.dump()
    # print(dir(dogtail.utils))
    # https://gitlab.com/dogtail/dogtail
    # ['Blinker', 'GLib', 'GnomeShell', 'Gtk', 'Highlight', 'Lock', 'TimeStamp', '__author__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'a11yDConfKey', 'absolute_import', 'bailBecauseA11yIsDisabled', 'cairo', 'checkForA11y', 'checkForA11yInteractively', 'config', 'division', 'doDelay', 'enableA11y', 'errno', 'gi', 'isA11yEnabled', 'logger', 'os', 'predicate', 'print_function', 'run', 'screenshot', 'shlex', 'sleep', 'subprocess', 'sys', 'unicode_literals']
    # what is this?
# this is the core.
nextTool()
# we can access online repl and more.
# [application | code]
#  [action |  |  ]
#  [frame | Mainshot.py - lazero - Visual Studio Code [Superuser]]
#   [action |  |  ]
#   [panel | ]
#    [action |  |  ]
#    [panel | ]
#     [action |  |  ]
#    [panel | ]
#     [action |  |  ]
#     [panel | ]
#      [action |  |  ]
#      [panel | ]
#       [action |  |  ]
#       [push button | File]
#        [action |  |  ]
#        [redundant object | ]
#         [action |  |  ]
#        [redundant object | ]
#         [action |  |  ]
#        [redundant object | File]
#         [action |  |  ]
#       [push button | Edit]
#        [action |  |  ]
#        [redundant object | ]
#         [action |  |  ]
#        [redundant object | ]
#         [action |  |  ]
#        [redundant object | Edit]
#         [action |  |  ]
#       [push button | Selection]
#        [action |  |  ]
#        [redundant object | ]
#         [action |  |  ]
#        [redundant object | ]
#         [action |  |  ]
#        [redundant object | Selection]
#         [action |  |  ]
#       [push button | View]
#        [action |  |  ]
#        [redundant object | ]
#         [action |  |  ]
#        [redundant object | ]
#         [action |  |  ]
#        [redundant object | View]
#         [action |  |  ]
#       [push button | Go]
#        [action |  |  ]
#        [redundant object | ]
#         [action |  |  ]
#        [redundant object | ]
#         [action |  |  ]
#        [redundant object | Go]
#         [action |  |  ]
#       [push button | Run]
#        [action |  |  ]
#        [redundant object | ]
#         [action |  |  ]
#        [redundant object | ]
#         [action |  |  ]
#        [redundant object | Run]
#         [action |  |  ]
#       [push button | Terminal]
#        [action |  |  ]
#        [redundant object | ]
#         [action |  |  ]
#        [redundant object | ]
#         [action |  |  ]
#        [redundant object | Terminal]
#         [action |  |  ]
#       [push button | Help]
#        [action |  |  ]
#        [redundant object | ]
#         [action |  |  ]
#        [redundant object | ]
#         [action |  |  ]
#        [redundant object | Help]
#         [action |  |  ]
#      [panel | ]
#       [action |  |  ]
#       [document web | ]
#        [action |  |  ]
#        [panel | ]
#         [action |  |  ]
#       [document web | ]
#        [action |  |  ]
#  [frame | Code]
#   [action |  |  ]
#   [panel | ]
#    [action |  |  ]
#    [panel | ]
#     [action |  |  ]
#    [panel | ]
#     [action |  |  ]
#     [panel | ]
#      [action |  |  ]
#      [panel | ]
#       [action |  |  ]
#       [push button | File]
#        [action |  |  ]
#        [redundant object | ]
#         [action |  |  ]
#        [redundant object | ]
#         [action |  |  ]
#        [redundant object | File]
#         [action |  |  ]
#       [push button | Edit]
#        [action |  |  ]
#        [redundant object | ]
#         [action |  |  ]
#        [redundant object | ]
#         [action |  |  ]
#        [redundant object | Edit]
#         [action |  |  ]
#       [push button | Selection]
#        [action |  |  ]
#        [redundant object | ]
#         [action |  |  ]
#        [redundant object | ]
#         [action |  |  ]
#        [redundant object | Selection]
#         [action |  |  ]
#       [push button | View]
#        [action |  |  ]
#        [redundant object | ]
#         [action |  |  ]
#        [redundant object | ]
#         [action |  |  ]
#        [redundant object | View]
#         [action |  |  ]
#       [push button | Go]
#        [action |  |  ]
#        [redundant object | ]
#         [action |  |  ]
#        [redundant object | ]
#         [action |  |  ]
#        [redundant object | Go]
#         [action |  |  ]
#       [push button | Run]
#        [action |  |  ]
#        [redundant object | ]
#         [action |  |  ]
#        [redundant object | ]
#         [action |  |  ]
#        [redundant object | Run]
#         [action |  |  ]
#       [push button | Terminal]
#        [action |  |  ]
#        [redundant object | ]
#         [action |  |  ]
#        [redundant object | ]
#         [action |  |  ]
#        [redundant object | Terminal]
#         [action |  |  ]
#       [push button | Help]
#        [action |  |  ]
#        [redundant object | ]
#         [action |  |  ]
#        [redundant object | ]
#         [action |  |  ]
#        [redundant object | Help]
#         [action |  |  ]
#      [panel | ]
#       [action |  |  ]
#       [document web | ]
#        [action |  |  ]
#        [panel | ]
#         [action |  |  ]
#       [document web | ]
#        [action |  |  ]
# finally get the name right? but is it about guessing or logic?
# fuzzy logic is guessing anyway.
# [application | zenmap]
#  [frame | Zenmap]
#   [filler | ]
#    [menu bar | ]
#     [menu | Scan]
#      [action | click | <Alt>a;<Alt>a; ]
#      [tearoff menu item | ]
#       [action | click |  ]
#      [menu item | New Window]
#       [action | click | n;<Alt>a:n;<Primary>n ]
#      [menu item | Open Scan]
#       [action | click | o;<Alt>a:o;<Primary>o ]
#      [menu item | Open Scan in This Window]
#       [action | click | o;<Alt>a:o; ]
#      [separator | ]
#       [action | click |  ]
#      [separator | ]
#       [action | click |  ]
#      [menu item | Save Scan]
#       [action | click | s;<Alt>a:s;<Primary>s ]
#      [menu item | Save All Scans to Directory]
#       [action | click | d;<Alt>a:d;<Primary><Alt>s ]
#      [separator | ]
#       [action | click |  ]
#      [menu item | Print...]
#       [action | click | ;; ]
#      [separator | ]
#       [action | click |  ]
#      [menu item | Close Window]
#       [action | click | ;;<Primary>w ]
#      [menu item | Quit]
#       [action | click | ;;<Primary>q ]
#      [menu item | Empty]
#       [action | click |  ]
#     [menu | Tools]
#      [action | click | <Alt>t;<Alt>t; ]
#      [tearoff menu item | ]
#       [action | click |  ]
#      [menu item | Compare Results]
#       [action | click | ;;<Primary>d ]
#      [menu item | Search Scan Results]
#       [action | click | ;;<Primary>f ]
#      [menu item | Filter Hosts]
#       [action | click | ;;<Primary>l ]
#      [menu item | Empty]
#       [action | click |  ]
#     [menu | Profile]
#      [action | click | <Alt>p;<Alt>p; ]
#      [tearoff menu item | ]
#       [action | click |  ]
#      [menu item | New Profile or Command]
#       [action | click | p;<Alt>p:p;<Primary>p ]
#      [menu item | Edit Selected Profile]
#       [action | click | e;<Alt>p:e;<Primary>e ]
#      [menu item | Empty]
#       [action | click |  ]
#     [menu | Help]
#      [action | click | <Alt>h;<Alt>h; ]
#      [tearoff menu item | ]
#       [action | click |  ]
#      [menu item | Help]
#       [action | click | h;<Alt>h:h;<Primary>h ]
#      [menu item | Report a bug]
#       [action | click | r;<Alt>h:r;<Primary>b ]
#      [menu item | About]
#       [action | click | a;<Alt>h:a; ]
#      [menu item | Empty]
#       [action | click |  ]
#    [filler | ]
#     [filler | ]
#      [filler | ]
#       [label | Target:]
#       [combo box | ]
#        [action | press |  ]
#        [menu | ]
#         [menu item | 183.207.204.197]
#          [action | click |  ]
#         [menu item | 8.8.8.8]
#          [action | click |  ]
#        [text | ]
#         [action | activate |  ]
#       [label | Profile:]
#       [combo box | Intense scan]
#        [action | press |  ]
#        [menu | ]
#         [menu item | Intense scan]
#          [action | click |  ]
#         [menu item | Intense scan plus UDP]
#          [action | click |  ]
#         [menu item | Intense scan, all TCP ports]
#          [action | click |  ]
#         [menu item | Intense scan, no ping]
#          [action | click |  ]
#         [menu item | Ping scan]
#          [action | click |  ]
#         [menu item | Quick scan]
#          [action | click |  ]
#         [menu item | Quick scan plus]
#          [action | click |  ]
#         [menu item | Quick traceroute]
#          [action | click |  ]
#         [menu item | Regular scan]
#          [action | click |  ]
#         [menu item | Slow comprehensive scan]
#          [action | click |  ]
#        [text | ]
#         [action | activate |  ]
#       [push button | Scan]
#        [action | click |  ]
#        [action | press |  ]
#        [action | release |  ]
#       [push button | Cancel]
#        [action | click |  ]
#        [action | press |  ]
#        [action | release |  ]
#      [filler | ]
#       [label | Command:]
#       [text | ]
#        [action | activate |  ]
#     [split pane | ]
#      [filler | ]
#       [filler | ]
#        [filler | ]
#         [filler | ]
#          [toggle button | Hosts]
#           [action | click |  ]
#           [action | press |  ]
#           [action | release |  ]
#          [toggle button | Services]
#           [action | click |  ]
#           [action | press |  ]
#           [action | release |  ]
#         [scroll pane | ]
#          [table | ]
#           [table column header | OS]
#            [action | click |  ]
#            [action | press |  ]
#            [action | release |  ]
#           [table column header | Host]
#            [action | click |  ]
#            [action | press |  ]
#            [action | release |  ]
#       [toggle button | Filter Hosts]
#        [action | click |  ]
#        [action | press |  ]
#        [action | release |  ]
#      [page tab list | ]
#       [page tab | Nmap Output]
#        [filler | ]
#         [filler | ]
#          [filler | ]
#           [combo box | ]
#            [action | press |  ]
#            [menu | ]
#           [icon | ]
#           [push button | Details]
#            [action | click |  ]
#            [action | press |  ]
#            [action | release |  ]
#          [filler | ]
#           [scroll pane | ]
#            [text | ]
#       [page tab | Ports / Hosts]
#        [filler | ]
#         [scroll pane | ]
#          [viewport | ]
#           [filler | ]
#            [scroll pane | ]
#             [table | ]
#              [table column header | Host]
#               [action | click |  ]
#               [action | press |  ]
#               [action | release |  ]
#              [table column header | ]
#               [action | click |  ]
#               [action | press |  ]
#               [action | release |  ]
#              [table column header | Port]
#               [action | click |  ]
#               [action | press |  ]
#               [action | release |  ]
#              [table column header | Protocol]
#               [action | click |  ]
#               [action | press |  ]
#               [action | release |  ]
#              [table column header | State]
#               [action | click |  ]
#               [action | press |  ]
#               [action | release |  ]
#              [table column header | Service]
#               [action | click |  ]
#               [action | press |  ]
#               [action | release |  ]
#              [table column header | Version]
#               [action | click |  ]
#               [action | press |  ]
#               [action | release |  ]
#       [page tab | Topology]
#        [filler | ]
#         [filler | ]
#          [filler | ]
#           [push button | Hosts Viewer]
#            [action | click |  ]
#            [action | press |  ]
#            [action | release |  ]
#           [toggle button | Fisheye]
#            [action | click |  ]
#            [action | press |  ]
#            [action | release |  ]
#           [toggle button | Controls]
#            [action | click |  ]
#            [action | press |  ]
#            [action | release |  ]
#           [push button | Legend]
#            [action | click |  ]
#            [action | press |  ]
#            [action | release |  ]
#           [push button | Save Graphic]
#            [action | click |  ]
#            [action | press |  ]
#            [action | release |  ]
#          [filler | ]
#           [filler | ]
#            [filler | ]
#             [filler | ]
#              [label | ]
#              [push button | Show the topology anyway]
#               [action | click |  ]
#               [action | press |  ]
#               [action | release |  ]
#             [unknown | ]
#            [filler | ]
#             [toggle button | Action]
#              [action | activate |  ]
#              [panel | ]
#               [filler | ]
#                [panel | ]
#                 [panel | ]
#                  [radio button | Color]
#                   [action | click |  ]
#                   [action | press |  ]
#                   [action | release |  ]
#                 [panel | ]
#                  [radio button | Add]
#                   [action | click |  ]
#                   [action | press |  ]
#                   [action | release |  ]
#                 [panel | ]
#                  [radio button | Information]
#                   [action | click |  ]
#                   [action | press |  ]
#                   [action | release |  ]
#                 [panel | ]
#                  [radio button | Jump to]
#                   [action | click |  ]
#                   [action | press |  ]
#                   [action | release |  ]
#                [combo box | Red]
#                 [action | press |  ]
#                 [menu | ]
#                  [menu item | Red]
#                   [action | click |  ]
#                  [menu item | Yellow]
#                   [action | click |  ]
#                  [menu item | Green]
#                   [action | click |  ]
#             [toggle button | Interpolation]
#              [action | activate |  ]
#              [panel | ]
#               [filler | ]
#                [filler | ]
#                 [label | Frames]
#                 [spin button | ]
#                  [action | activate |  ]
#                [filler | ]
#                 [radio button | Polar]
#                  [action | click |  ]
#                  [action | press |  ]
#                  [action | release |  ]
#                 [radio button | Cartesian]
#                  [action | click |  ]
#                  [action | press |  ]
#                  [action | release |  ]
#             [toggle button | Layout]
#              [action | activate |  ]
#              [panel | ]
#               [filler | ]
#                [combo box | Weighted]
#                 [action | press |  ]
#                 [menu | ]
#                  [menu item | Symmetric]
#                   [action | click |  ]
#                  [menu item | Weighted]
#                   [action | click |  ]
#                [panel | ]
#                 [push button | Refresh]
#                  [action | click |  ]
#                  [action | press |  ]
#                  [action | release |  ]
#             [toggle button | View]
#              [action | activate |  ]
#              [panel | ]
#               [filler | ]
#                [scroll pane | ]
#                 [viewport | ]
#                  [table | ]
#                   [table column header | ]
#                    [action | click |  ]
#                    [action | press |  ]
#                    [action | release |  ]
#                   [table column header | ]
#                    [action | click |  ]
#                    [action | press |  ]
#                    [action | release |  ]
#                   [table cell | ]
#                    [action | activate |  ]
#                    [action | toggle |  ]
#                   [table cell | address]
#                    [action | activate |  ]
#                   [table cell | ]
#                    [action | activate |  ]
#                    [action | toggle |  ]
#                   [table cell | hostname]
#                    [action | activate |  ]
#                   [table cell | ]
#                    [action | activate |  ]
#                    [action | toggle |  ]
#                   [table cell | icon]
#                    [action | activate |  ]
#                   [table cell | ]
#                    [action | activate |  ]
#                    [action | toggle |  ]
#                   [table cell | latency]
#                    [action | activate |  ]
#                   [table cell | ]
#                    [action | activate |  ]
#                    [action | toggle |  ]
#                   [table cell | ring]
#                    [action | activate |  ]
#                   [table cell | ]
#                    [action | activate |  ]
#                    [action | toggle |  ]
#                   [table cell | region]
#                    [action | activate |  ]
#                   [table cell | ]
#                    [action | activate |  ]
#                    [action | toggle |  ]
#                   [table cell | slow in/out]
#                    [action | activate |  ]
#                [unknown | ]
#                [filler | ]
#                 [push button | ]
#                  [action | click |  ]
#                  [action | press |  ]
#                  [action | release |  ]
#                 [unknown | ]
#                 [push button | ]
#                  [action | click |  ]
#                  [action | press |  ]
#                  [action | release |  ]
#                [filler | ]
#                 [filler | ]
#                  [push button | ]
#                   [action | click |  ]
#                   [action | press |  ]
#                   [action | release |  ]
#                  [unknown | ]
#                  [push button | ]
#                   [action | click |  ]
#                   [action | press |  ]
#                   [action | release |  ]
#                 [filler | ]
#                  [label | Lower ring gap]
#                  [spin button | ]
#                   [action | activate |  ]
#           [filler | ]
#            [filler | ]
#             [label | Fisheye on ring]
#             [spin button | ]
#              [action | activate |  ]
#             [slider | ]
#              [action | activate |  ]
#             [label | with interest factor]
#             [spin button | ]
#              [action | activate |  ]
#             [label | and spread factor]
#             [spin button | ]
#              [action | activate |  ]
#       [page tab | Host Details]
#        [scroll pane | ]
#         [viewport | ]
#          [filler | ]
#           [label | No host selected.]
#       [page tab | Scans]
#        [filler | ]
#         [filler | ]
#          [scroll pane | ]
#           [table | ]
#            [table column header | Status]
#             [action | click |  ]
#             [action | press |  ]
#             [action | release |  ]
#            [table column header | Command]
#             [action | click |  ]
#             [action | press |  ]
#             [action | release |  ]
#          [filler | ]
#           [filler | ]
#            [push button | Append Scan]
#             [action | click |  ]
#             [action | press |  ]
#             [action | release |  ]
#            [push button | Remove Scan]
#             [action | click |  ]
#             [action | press |  ]
#             [action | release |  ]
#            [push button | Cancel Scan]
#             [action | click |  ]
#             [action | press |  ]
#             [action | release |  ]
#     [filler | ]
#      [label | ]
#      [label | Host Filter:]
#      [text | ]
#       [action | activate |  ]
#      [push button | Information]
#       [action | click |  ]
#       [action | press |  ]
#       [action | release |  ]