#!/bin/bash
cd zero
./AS &
./BusyBox &
./Compos &
./FFI &
./FileCheck &
./GNU &
./Git &
./PRoot &
./SDLKey &
./SDL_ActiveEvent &
./SDL_AddTimer &
./SDL_AudioCVT &
./SDL_AudioSpec &
./SDL_BlitSurface &
./SDL_BuildAudioCVT &
./SDL_CD &
./SDL_CDClose &
./SDL_CDEject &
./SDL_CDName &
./SDL_CDNumDrives &
./SDL_CDOpen &
./SDL_CDPause &
./SDL_CDPlay &
./SDL_CDPlayTracks &
./SDL_CDResume &
./SDL_CDStatus &
./SDL_CDStop &
./SDL_CDtrack &
./SDL_CloseAudio &
./SDL_Color &
./SDL_CondBroadcast &
./SDL_CondSignal &
./SDL_CondWait &
./SDL_CondWaitTimeout &
./SDL_ConvertAudio &
./SDL_ConvertSurface &
./SDL_CreateCond &
./SDL_CreateCursor &
./SDL_CreateMutex &
./SDL_CreateRGBSurface &
./SDL_CreateRGBSurfaceFrom &
./SDL_CreateSemaphore &
./SDL_CreateThread &
./SDL_CreateYUVOverlay &
./SDL_Delay &
./SDL_DestroyCond &
./SDL_DestroyMutex &
./SDL_DestroySemaphore &
./SDL_DisplayFormat &
./SDL_DisplayFormatAlpha &
./SDL_DisplayYUVOverlay &
./SDL_EnableKeyRepeat &
./SDL_EnableUNICODE &
./SDL_Event &
./SDL_EventState &
./SDL_ExposeEvent &
./SDL_FillRect &
./SDL_Flip &
./SDL_FreeCursor &
./SDL_FreeSurface &
./SDL_FreeWAV &
./SDL_FreeYUVOverlay &
./SDL_FunctionName &
./SDL_GL_GetAttribute &
./SDL_GL_GetProcAddress &
./SDL_GL_LoadLibrary &
./SDL_GL_SetAttribute &
./SDL_GL_SwapBuffers &
./SDL_GLattr &
./SDL_GetAppState &
./SDL_GetAudioStatus &
./SDL_GetClipRect &
./SDL_GetCursor &
./SDL_GetError &
./SDL_GetEventFilter &
./SDL_GetGamma &
./SDL_GetGammaRamp &
./SDL_GetKeyName &
./SDL_GetKeyState &
./SDL_GetModState &
./SDL_GetMouseState &
./SDL_GetRGB &
./SDL_GetRGBA &
./SDL_GetRelativeMouseState &
./SDL_GetThreadID &
./SDL_GetTicks &
./SDL_GetVideoInfo &
./SDL_GetVideoSurface &
./SDL_Init &
./SDL_InitSubSystem &
./SDL_JoyAxisEvent &
./SDL_JoyBallEvent &
./SDL_JoyButtonEvent &
./SDL_JoyHatEvent &
./SDL_JoystickClose &
./SDL_JoystickEventState &
./SDL_JoystickGetAxis &
./SDL_JoystickGetBall &
./SDL_JoystickGetButton &
./SDL_JoystickGetHat &
./SDL_JoystickIndex &
./SDL_JoystickName &
./SDL_JoystickNumAxes &
./SDL_JoystickNumBalls &
./SDL_JoystickNumButtons &
./SDL_JoystickNumHats &
./SDL_JoystickOpen &
./SDL_JoystickOpened &
./SDL_JoystickUpdate &
./SDL_KeyboardEvent &
./SDL_KillThread &
./SDL_ListModes &
./SDL_LoadBMP &
./SDL_LoadWAV &
./SDL_LockAudio &
./SDL_LockSurface &
./SDL_LockYUVOverlay &
./SDL_MapRGB &
./SDL_MapRGBA &
./SDL_MixAudio &
./SDL_MouseButtonEvent &
./SDL_MouseMotionEvent &
./SDL_NumJoysticks &
./SDL_OpenAudio &
./SDL_Overlay &
./SDL_Palette &
./SDL_PauseAudio &
./SDL_PeepEvents &
./SDL_PixelFormat &
./SDL_PollEvent &
./SDL_PumpEvents &
./SDL_PushEvent &
./SDL_Quit &
./SDL_QuitEvent &
./SDL_QuitSubSystem &
./SDL_RWFromFil &
./SDL_Rect &
./SDL_RemoveTimer &
./SDL_ResizeEvent &
./SDL_SaveBMP &
./SDL_SemPost &
./SDL_SemTryWait &
./SDL_SemValue &
./SDL_SemWait &
./SDL_SemWaitTimeout &
./SDL_SetAlpha &
./SDL_SetClipRect &
./SDL_SetColorKey &
./SDL_SetColors &
./SDL_SetCursor &
./SDL_SetEventFilter &
./SDL_SetGamma &
./SDL_SetGammaRamp &
./SDL_SetModState &
./SDL_SetPalette &
./SDL_SetTimer &
./SDL_SetVideoMode &
./SDL_ShowCursor &
./SDL_Surface &
./SDL_SysWMEvent &
./SDL_ThreadID &
./SDL_UnlockAudio &
./SDL_UnlockSurface &
./SDL_UnlockYUVOverlay &
./SDL_UpdateRect &
./SDL_UpdateRects &
./SDL_UserEvent &
./SDL_VideoDriverName &
./SDL_VideoInfo &
./SDL_VideoModeOK &
./SDL_WM_GetCaption &
./SDL_WM_GrabInput &
./SDL_WM_IconifyWindow &
./SDL_WM_SetCaption &
./SDL_WM_SetIcon &
./SDL_WM_ToggleFullScreen &
./SDL_WaitEvent &
./SDL_WaitThread &
./SDL_WarpMouse &
./SDL_WasInit &
./SDL_keysym &
./SDL_mutexP &
./SDL_mutexV &
./Wget &
./XCompose &
./a &
./acyclic &
./addgnupghome &
./addpart &
./addr2line &
./adjtime &
./adjtime_confi &
./applygnupgdefaults &
./apropo &
./ar &
./aria2c &
./aria_chk &
./aria_dump_log &
./aria_ftdump &
./aria_pack &
./aria_read_log &
./axel &
./b2sum &
./badblocks &
./base32 &
./base64 &
./basename &
./basenc &
./bash &
./bc &
./bcomps &
./blkdiscard &
./blkid &
./blkzone &
./blockdev &
./bugpoint &
./busybo &
./c++filt &
./cal &
./cargo &
./cargo-bench &
./cargo-build &
./cargo-check &
./cargo-clean &
./cargo-doc &
./cargo-fetch &
./cargo-generate-lockfile &
./cargo-init &
./cargo-install &
./cargo-login &
./cargo-metadata &
./cargo-new &
./cargo-owner &
./cargo-package &
./cargo-pkgid &
./cargo-publish &
./cargo-run &
./cargo-rustc &
./cargo-rustdoc &
./cargo-search &
./cargo-test &
./cargo-uninstall &
./cargo-update &
./cargo-version &
./cargo-yank &
./cat &
./ccomps &
./certtool &
./chattr &
./chcon &
./chcpu &
./chgrp &
./chmod &
./choom &
./chown &
./chrt &
./ci &
./circ &
./cksum &
./clear &
./cluster &
./cm &
./co &
./col &
./colcrt &
./colrm &
./column &
./comm &
./compile_et &
./coreutils &
./cp &
./cpio &
./csplit &
./ctags &
./ctrlaltdel &
./curl &
./curl-config &
./cut &
./das &
./date &
./dc &
./dd &
./deb-version &
./debugfs &
./default.pa &
./delpart &
./demandoc &
./dif &
./diff &
./diffimg &
./dijkstra &
./dir &
./dircolors &
./dirmngr &
./dirmngr-client &
./dirname &
./dlltool &
./dmesg &
./do &
./dotty &
./dpkg &
./dpkg-deb &
./dpkg-divert &
./dpkg-genbuildinfo &
./dpkg-query &
./dpkg-split &
./dpkg-trigger &
./dsymutil &
./du &
./dumpe2fs &
./e2freefrag &
./e2fsc &
./e2fsck.conf &
./e2image &
./e2label &
./e2mmpstatus &
./e2scrub &
./e2scrub_all &
./e2undo &
./e4crypt &
./ebrowse &
./echo &
./ed2k-lin &
./edgepaint &
./editrc &
./edonr256-has &
./edonr512-has &
./egre &
./elfedit &
./emacs &
./emacsclient &
./eqn &
./etag &
./expand &
./expr &
./ext &
./ext4 &
./factor &
./fallocate &
./false &
./fd &
./fdformat &
./ff &
./ffi_cal &
./ffi_call &
./ffi_cif &
./ffi_prep_ci &
./ffi_prep_cif_va &
./fgrep &
./filefrag &
./fincore &
./findfs &
./fish &
./fish_indent &
./fish_key_reader &
./flex &
./flock &
./fmt &
./fold &
./freetype-config &
./fsck &
./fsck.cramfs &
./fsck.ext &
./fsck.ext4 &
./fsck.minix &
./fsfreeze &
./galera_new_cluster &
./galera_recovery &
./gc &
./gdbm_dump &
./gdbm_load &
./gdbmtool &
./gdk-pixbuf-csource &
./gdk-pixbuf-query-loaders &
./getconf &
./getopt &
./git &
./git-add &
./git-am &
./git-annotate &
./git-apply &
./git-archimport &
./git-archive &
./git-bisect &
./git-blame &
./git-branch &
./git-bundle &
./git-cat-file &
./git-check-attr &
./git-check-ignore &
./git-check-mailmap &
./git-check-ref-format &
./git-checkout &
./git-checkout-index &
./git-cherry &
./git-cherry-pick &
./git-citool &
./git-clean &
./git-clone &
./git-column &
./git-commit &
./git-commit-graph &
./git-commit-tree &
./git-config &
./git-count-objects &
./git-credential &
./git-credential-cache &
./git-credential-cache--daemon &
./git-credential-store &
./git-cvsexportcommit &
./git-cvsimport &
./git-daemon &
./git-describe &
./git-diff &
./git-diff-files &
./git-diff-index &
./git-diff-tree &
./git-difftool &
./git-fast-export &
./git-fast-import &
./git-fetch &
./git-fetch-pack &
./git-filter-branch &
./git-fmt-merge-msg &
./git-for-each-ref &
./git-format-patch &
./git-fsck &
./git-fsck-objects &
./git-gc &
./git-get-tar-commit-id &
./git-grep &
./git-gui &
./git-hash-object &
./git-help &
./git-http-backend &
./git-http-fetch &
./git-http-push &
./git-imap-send &
./git-index-pack &
./git-init &
./git-init-db &
./git-instaweb &
./git-interpret-trailers &
./git-log &
./git-ls-files &
./git-ls-remote &
./git-ls-tree &
./git-mailinfo &
./git-mailsplit &
./git-merge &
./git-merge-base &
./git-merge-file &
./git-merge-index &
./git-merge-one-file &
./git-merge-tree &
./git-mergetool &
./git-mergetool--lib &
./git-mktag &
./git-mktree &
./git-multi-pack-index &
./git-mv &
./git-name-rev &
./git-notes &
./git-p4 &
./git-pack-objects &
./git-pack-redundant &
./git-pack-refs &
./git-parse-remote &
./git-patch-id &
./git-prune &
./git-prune-packed &
./git-pull &
./git-push &
./git-quiltimport &
./git-range-diff &
./git-read-tree &
./git-rebase &
./git-receive-pack &
./git-reflog &
./git-remote &
./git-remote-ext &
./git-remote-fd &
./git-repack &
./git-replace &
./git-request-pull &
./git-rerere &
./git-reset &
./git-rev-list &
./git-rev-parse &
./git-revert &
./git-rm &
./git-send-email &
./git-send-pack &
./git-sh-i18n &
./git-sh-i18n--envsubst &
./git-sh-setup &
./git-shortlog &
./git-show &
./git-show-branch &
./git-show-index &
./git-show-ref &
./git-stage &
./git-stash &
./git-status &
./git-stripspace &
./git-submodule &
./git-subtree &
./git-svn &
./git-symbolic-ref &
./git-tag &
./git-unpack-file &
./git-unpack-objects &
./git-update-index &
./git-update-ref &
./git-update-server-info &
./git-upload-archive &
./git-upload-pack &
./git-var &
./git-verify-commit &
./git-verify-pack &
./git-verify-tag &
./git-web--browse &
./git-whatchanged &
./git-worktree &
./git-write-tree &
./gitattributes &
./gitcli &
./gitcore-tutorial &
./gitcredentials &
./gitcvs-migration &
./gitdiffcore &
./giteveryday &
./gitglossary &
./githooks &
./gitignore &
./gitk &
./gitmodules &
./gitnamespaces &
./gitremote-helpers &
./gitrepository-layout &
./gitrevisions &
./gitsubmodules &
./gittutorial &
./gittutorial-2 &
./gitweb &
./gitweb.conf &
./gitworkflows &
./gml2g &
./gnutls-cli &
./gnutls-cli-debug &
./gnutls-serv &
./gost-has &
./gpg &
./gpg-agent &
./gpg-connect-agent &
./gpg-preset-passphrase &
./gpg-wks-client &
./gpg-wks-server &
./gpgconf &
./gpgparsemail &
./gpgrt-config &
./gpgsm &
./gpgtar &
./gpgv &
./gprof &
./graphml2gv &
./graphviz &
./gre &
./groups &
./gv2gml &
./gv2gxl &
./gvcolor &
./gvgen &
./gvmap &
./gvmap.sh &
./gvpack &
./gvpr &
./gxl2g &
./has160-has &
./head &
./hexdump &
./hmac256 &
./hwclock &
./iconv &
./iconv_close &
./iconv_open &
./iconv_open_into &
./iconvctl &
./id &
./ident &
./idn2 &
./infocmp &
./innochecksum &
./install &
./ionice &
./ipython &
./isosize &
./isympy &
./join &
./k5identit &
./k5logi &
./k5srvutil &
./kadm5.acl &
./kadmi &
./kadmin.local &
./kadmind &
./kdb5_ldap_util &
./kdb5_util &
./kdc.conf &
./kdestroy &
./kerberos &
./kill &
./kinit &
./klist &
./kpasswd &
./kprop &
./kpropd &
./kproplog &
./krb5-config &
./krb5.conf &
./krb5kdc &
./ksu &
./kswitch &
./ktutil &
./kvno &
./ld &
./ldattach &
./lefty &
./less &
./lessecho &
./lesskey &
./libarchive-formats &
./libexslt &
./libpng &
./libpngp &
./libtool &
./libtoolize &
./libxml &
./libxslt &
./link &
./linux3 &
./linux6 &
./lit &
./llc &
./lli &
./llvm-ar &
./llvm-as &
./llvm-bcanalyzer &
./llvm-build &
./llvm-config &
./llvm-cov &
./llvm-cxxmap &
./llvm-diff &
./llvm-dis &
./llvm-dwarfdump &
./llvm-exegesis &
./llvm-extract &
./llvm-lib &
./llvm-link &
./llvm-mca &
./llvm-nm &
./llvm-objdump &
./llvm-pdbutil &
./llvm-profdata &
./llvm-readobj &
./llvm-stress &
./llvm-symbolizer &
./ln &
./lneato &
./locate &
./logname &
./logsave &
./look &
./losetup &
./ls &
./lsattr &
./lscpu &
./lsipc &
./lynx &
./lzca &
./lzcm &
./lzdiff &
./lzegre &
./lzfgre &
./lzgre &
./lzless &
./lzm &
./lzmadec &
./lzmainfo &
./lzmore &
./m4 &
./magnet-lin &
./make &
./makewhatis &
./man &
./man.conf &
./mandoc &
./mandoc.db &
./mandoc_char &
./mariabackup &
./mariadb-service-convert &
./mbstream &
./mcookie &
./md5sum &
./mdoc &
./merge &
./mesg &
./mingle &
./mkdir &
./mke2f &
./mke2fs.conf &
./mkfifo &
./mkfs &
./mkfs.bfs &
./mkfs.cramfs &
./mkfs.ext &
./mkfs.ext4 &
./mkfs.minix &
./mklost+found &
./mknod &
./mkswap &
./mktemp &
./mlocate.db &
./mm2gv &
./moduli &
./more &
./msql2mysql &
./mtree &
./mv &
./my_print_defaults &
./my_safe_process &
./myisam_ftdump &
./myisamchk &
./myisamlog &
./myisampack &
./mysq &
./mysql-stress-test.pl &
./mysql.server &
./mysql_client_tes &
./mysql_client_test_embedded &
./mysql_config &
./mysql_convert_table_format &
./mysql_embedded &
./mysql_find_rows &
./mysql_fix_extensions &
./mysql_install_db &
./mysql_ldb &
./mysql_plugin &
./mysql_secure_installation &
./mysql_setpermission &
./mysql_tzinfo_to_sql &
./mysql_upgrade &
./mysql_waitpid &
./mysqlaccess &
./mysqladmin &
./mysqlbinlog &
./mysqlcheck &
./mysqld &
./mysqld_multi &
./mysqld_safe &
./mysqld_safe_helper &
./mysqldump &
./mysqldumpslow &
./mysqlhotcopy &
./mysqlimport &
./mysqlshow &
./mysqlslap &
./mysqltes &
./mysqltest_embedded &
./n &
./namei &
./nano &
./nanorc &
./nca &
./neat &
./netcat &
./nginx &
./nice &
./nl &
./nm &
./nmap &
./node &
./nohup &
./nologin &
./nop &
./nping &
./nproc &
./nsenter &
./numfmt &
./objcopy &
./objdump &
./ocsptool &
./od &
./opt &
./osage &
./p11tool &
./paca &
./pacmd &
./pactl &
./padsp &
./pamo &
./pango-view &
./papla &
./pare &
./parecord &
./partx &
./paste &
./pasuspender &
./patchwork &
./pathchk &
./pax11publish &
./pcap-filter &
./pcap-linktype &
./pcap-savefile &
./pcap-tstamp &
./perror &
./pkg-config &
./png &
./pr &
./printenv &
./printf &
./prlimit &
./proo &
./prune &
./psktool &
./ptx &
./pulse-cli-syntax &
./pulse-client.conf &
./pulse-daemon.conf &
./pulseaudio &
./pv &
./pwd &
./pytho &
./python &
./python2. &
./python3.7 &
./ranlib &
./raw &
./rclone &
./rcs &
./rcsclean &
./rcsdiff &
./rcsfile &
./rcsmerge &
./readelf &
./readlink &
./readprofile &
./realpath &
./rename &
./renice &
./replace &
./reset &
./resize2fs &
./resizepart &
./resolve_stack_dump &
./resolveip &
./rev &
./rhas &
./rlog &
./rm &
./rmdir &
./rmt &
./roff &
./rsvg-convert &
./rsync &
./rsyncd.conf &
./rtcwake &
./runcon &
./rustc &
./rustdoc &
./scan-build &
./sccmap &
./scdaemon &
./sclient &
./scp &
./script &
./scriptreplay &
./sdif &
./sed &
./seq &
./setarc &
./setsid &
./setterm &
./sfd &
./sftp &
./sftp-server &
./sfv-has &
./sh &
./sha1sum &
./sha224sum &
./sha256sum &
./sha384sum &
./sha512sum &
./shred &
./shuf &
./size &
./sleep &
./smyrna &
./soelim &
./sort &
./split &
./srptool &
./sserver &
./ssh &
./ssh-add &
./ssh-agent &
./ssh-copy-id &
./ssh-keygen &
./ssh-keyscan &
./ssh-keysign &
./ssh-pkcs11-helper &
./ssh_config &
./sshd &
./sshd_config &
./start-pulseaudio-x11 &
./stat &
./stdbuf &
./strace &
./strace-log-merge &
./strings &
./strip &
./stty &
./sum &
./swaplabel &
./symcryptrun &
./sync &
./tabs &
./tac &
./tail &
./tar &
./taskset &
./tbl &
./tblgen &
./tee &
./terminal-colors.d &
./test &
./tic &
./tiger-has &
./timeout &
./tmux &
./toe &
./tokuft_logprint &
./tokuftdump &
./touch &
./tpmtool &
./tpu &
./tr &
./tred &
./true &
./truncate &
./tse &
./tsort &
./tth-has &
./tty &
./tune2fs &
./twopi &
./ul &
./uname &
./uname26 &
./unexpand &
./unflatten &
./uniq &
./unlink &
./unlzm &
./unshare &
./unx &
./updatedb &
./updatedb.con &
./vdir &
./vi &
./view &
./vimdiff &
./vimdot &
./vimtutor &
./w3m &
./w3mman &
./watchgnupg &
./wc &
./wdctl &
./wge &
./whatis &
./whereis &
./whirlpool-hash &
./whoami &
./wipefs &
./wsrep_sst_common &
./wsrep_sst_mariabackup &
./wsrep_sst_mysqldump &
./wsrep_sst_rsync &
./wsrep_sst_rsync_wan &
./x &
./xauth &
./xml-config &
./xml2-confi &
./xmlcatalog &
./xmllint &
./xxd &
./xzcat &
./xzcm &
./xzde &
./xzdif &
./xzegre &
./xzfgrep &
./xzgre &
./xzles &
./xzmor &
./yes &
./zip &
./zipcloak &
./zipnote &
./zipsplit &
./zlib &
./zmq &
./zmq_atomic_counter_dec &
./zmq_atomic_counter_destroy &
./zmq_atomic_counter_inc &
./zmq_atomic_counter_new &
./zmq_atomic_counter_set &
./zmq_atomic_counter_value &
./zmq_bind &
./zmq_close &
./zmq_connect &
./zmq_ctx_get &
./zmq_ctx_new &
./zmq_ctx_set &
./zmq_ctx_shutdown &
./zmq_ctx_term &
./zmq_curve &
./zmq_curve_keypair &
./zmq_curve_public &
./zmq_disconnect &
./zmq_errno &
./zmq_getsockopt &
./zmq_gssapi &
./zmq_has &
./zmq_inproc &
./zmq_ipc &
./zmq_msg_close &
./zmq_msg_copy &
./zmq_msg_data &
./zmq_msg_get &
./zmq_msg_gets &
./zmq_msg_init &
./zmq_msg_init_data &
./zmq_msg_init_size &
./zmq_msg_more &
./zmq_msg_move &
./zmq_msg_recv &
./zmq_msg_routing_id &
./zmq_msg_send &
./zmq_msg_set &
./zmq_msg_set_routing_id &
./zmq_msg_size &
./zmq_null &
./zmq_pgm &
./zmq_plain &
./zmq_poll &
./zmq_poller &
./zmq_proxy &
./zmq_proxy_steerable &
./zmq_recv &
./zmq_recvmsg &
./zmq_send &
./zmq_send_const &
./zmq_sendmsg &
./zmq_setsockopt &
./zmq_socket &
./zmq_socket_monitor &
./zmq_strerror &
./zmq_tcp &
./zmq_timers &
./zmq_tipc &
./zmq_udp &
./zmq_unbind &
./zmq_version &
./zmq_vmci &
./zmq_z85_decode &
./zmq_z85_encode &
./zramctl &
./zsh &
./zshall &
./zshbuiltins &
./zshcalsys &
./zshcompctl &
./zshcompsys &
./zshcompwid &
./zshcontrib &
./zshexpn &
./zshmisc &
./zshmodules &
./zshoptions &
./zshparam &
./zshroadmap &
./zshtcpsys &
./zshzftpsys &
./zshzle &
