#!/bin/bash
curl 'https://github.com/google?page=1&tab=repositories' > 1.log
curl 'https://github.com/google?page=2&tab=repositories' > 2.log
curl 'https://github.com/google?page=3&tab=repositories' > 3.log
curl 'https://github.com/google?page=4&tab=repositories' > 4.log
curl 'https://github.com/google?page=5&tab=repositories' > 5.log
curl 'https://github.com/google?page=6&tab=repositories' > 6.log
curl 'https://github.com/google?page=7&tab=repositories' > 7.log
curl 'https://github.com/google?page=8&tab=repositories' > 8.log
curl 'https://github.com/google?page=9&tab=repositories' > 9.log
curl 'https://github.com/google?page=10&tab=repositories' > 10.log
curl 'https://github.com/google?page=11&tab=repositories' > 11.log
curl 'https://github.com/google?page=12&tab=repositories' > 12.log
curl 'https://github.com/google?page=13&tab=repositories' > 13.log
curl 'https://github.com/google?page=14&tab=repositories' > 14.log
curl 'https://github.com/google?page=15&tab=repositories' > 15.log
curl 'https://github.com/google?page=16&tab=repositories' > 16.log
curl 'https://github.com/google?page=17&tab=repositories' > 17.log
curl 'https://github.com/google?page=18&tab=repositories' > 18.log
curl 'https://github.com/google?page=19&tab=repositories' > 19.log
curl 'https://github.com/google?page=20&tab=repositories' > 20.log
curl 'https://github.com/google?page=21&tab=repositories' > 21.log
curl 'https://github.com/google?page=22&tab=repositories' > 22.log
curl 'https://github.com/google?page=23&tab=repositories' > 23.log
curl 'https://github.com/google?page=24&tab=repositories' > 24.log
curl 'https://github.com/google?page=25&tab=repositories' > 25.log
curl 'https://github.com/google?page=26&tab=repositories' > 26.log
curl 'https://github.com/google?page=27&tab=repositories' > 27.log
curl 'https://github.com/google?page=28&tab=repositories' > 28.log
curl 'https://github.com/google?page=29&tab=repositories' > 29.log
curl 'https://github.com/google?page=30&tab=repositories' > 30.log
curl 'https://github.com/google?page=31&tab=repositories' > 31.log
curl 'https://github.com/google?page=32&tab=repositories' > 32.log
curl 'https://github.com/google?page=33&tab=repositories' > 33.log
curl 'https://github.com/google?page=34&tab=repositories' > 34.log
curl 'https://github.com/google?page=35&tab=repositories' > 35.log
curl 'https://github.com/google?page=36&tab=repositories' > 36.log
curl 'https://github.com/google?page=37&tab=repositories' > 37.log
curl 'https://github.com/google?page=38&tab=repositories' > 38.log
curl 'https://github.com/google?page=39&tab=repositories' > 39.log
curl 'https://github.com/google?page=40&tab=repositories' > 40.log
curl 'https://github.com/google?page=41&tab=repositories' > 41.log
curl 'https://github.com/google?page=42&tab=repositories' > 42.log
curl 'https://github.com/google?page=43&tab=repositories' > 43.log
curl 'https://github.com/google?page=44&tab=repositories' > 44.log
curl 'https://github.com/google?page=45&tab=repositories' > 45.log
curl 'https://github.com/google?page=46&tab=repositories' > 46.log
curl 'https://github.com/google?page=47&tab=repositories' > 47.log
curl 'https://github.com/google?page=48&tab=repositories' > 48.log
curl 'https://github.com/google?page=49&tab=repositories' > 49.log
curl 'https://github.com/google?page=50&tab=repositories' > 50.log
curl 'https://github.com/google?page=51&tab=repositories' > 51.log
curl 'https://github.com/google?page=52&tab=repositories' > 52.log
curl 'https://github.com/google?page=53&tab=repositories' > 53.log
curl 'https://github.com/google?page=54&tab=repositories' > 54.log
curl 'https://github.com/google?page=55&tab=repositories' > 55.log
curl 'https://github.com/google?page=56&tab=repositories' > 56.log
curl 'https://github.com/google?page=57&tab=repositories' > 57.log
curl 'https://github.com/google?page=58&tab=repositories' > 58.log
curl 'https://github.com/google?page=59&tab=repositories' > 59.log
curl 'https://github.com/google?page=60&tab=repositories' > 60.log
curl 'https://github.com/google?page=61&tab=repositories' > 61.log
curl 'https://github.com/google?page=62&tab=repositories' > 62.log
curl 'https://github.com/google?page=63&tab=repositories' > 63.log
curl 'https://github.com/google?page=64&tab=repositories' > 64.log
curl 'https://github.com/google?page=65&tab=repositories' > 65.log
curl 'https://github.com/google?page=66&tab=repositories' > 66.log
curl 'https://github.com/google?page=67&tab=repositories' > 67.log
curl 'https://github.com/google?page=68&tab=repositories' > 68.log
curl 'https://github.com/google?page=69&tab=repositories' > 69.log
curl 'https://github.com/google?page=70&tab=repositories' > 70.log