#!/bin/bash
wget "https://unicode.org/charts/PDF/10FF80.pdf" &
wget "https://unicode.org/charts/PDF/ErrorLink.pdf" &
wget "https://unicode.org/charts/PDF/U0A00.pdf" &
wget "https://unicode.org/charts/PDF/U0A80.pdf" &
wget "https://unicode.org/charts/PDF/U0B00.pdf" &
wget "https://unicode.org/charts/PDF/U0B80.pdf" &
wget "https://unicode.org/charts/PDF/U0C00.pdf" &
wget "https://unicode.org/charts/PDF/U0C80.pdf" &
wget "https://unicode.org/charts/PDF/U0D00.pdf" &
wget "https://unicode.org/charts/PDF/U0D80.pdf" &
wget "https://unicode.org/charts/PDF/U0E00.pdf" &
wget "https://unicode.org/charts/PDF/U0E80.pdf" &
wget "https://unicode.org/charts/PDF/U0F00.pdf" &
wget "https://unicode.org/charts/PDF/U0000.pdf" &
wget "https://unicode.org/charts/PDF/U0080.pdf" &
wget "https://unicode.org/charts/PDF/U0100.pdf" &
wget "https://unicode.org/charts/PDF/U0180.pdf" &
wget "https://unicode.org/charts/PDF/U02B0.pdf" &
wget "https://unicode.org/charts/PDF/U0250.pdf" &
wget "https://unicode.org/charts/PDF/U0300.pdf" &
wget "https://unicode.org/charts/PDF/U0370.pdf" &
wget "https://unicode.org/charts/PDF/U0400.pdf" &
wget "https://unicode.org/charts/PDF/U0500.pdf" &
wget "https://unicode.org/charts/PDF/U0530.pdf" &
wget "https://unicode.org/charts/PDF/U0590.pdf" &
wget "https://unicode.org/charts/PDF/U0600.pdf" &
wget "https://unicode.org/charts/PDF/U07C0.pdf" &
wget "https://unicode.org/charts/PDF/U0700.pdf" &
wget "https://unicode.org/charts/PDF/U0750.pdf" &
wget "https://unicode.org/charts/PDF/U0780.pdf" &
wget "https://unicode.org/charts/PDF/U08A0.pdf" &
wget "https://unicode.org/charts/PDF/U0800.pdf" &
wget "https://unicode.org/charts/PDF/U0840.pdf" &
wget "https://unicode.org/charts/PDF/U0860.pdf" &
wget "https://unicode.org/charts/PDF/U0900.pdf" &
wget "https://unicode.org/charts/PDF/U0980.pdf" &
wget "https://unicode.org/charts/PDF/U1A00.pdf" &
wget "https://unicode.org/charts/PDF/U1A20.pdf" &
wget "https://unicode.org/charts/PDF/U1AB0.pdf" &
wget "https://unicode.org/charts/PDF/U1B00.pdf" &
wget "https://unicode.org/charts/PDF/U1B000.pdf" &
wget "https://unicode.org/charts/PDF/U1B80.pdf" &
wget "https://unicode.org/charts/PDF/U1B100.pdf" &
wget "https://unicode.org/charts/PDF/U1B130.pdf" &
wget "https://unicode.org/charts/PDF/U1B170.pdf" &
wget "https://unicode.org/charts/PDF/U1BC0.pdf" &
wget "https://unicode.org/charts/PDF/U1BC00.pdf" &
wget "https://unicode.org/charts/PDF/U1BCA0.pdf" &
wget "https://unicode.org/charts/PDF/U1C00.pdf" &
wget "https://unicode.org/charts/PDF/U1C50.pdf" &
wget "https://unicode.org/charts/PDF/U1C80.pdf" &
wget "https://unicode.org/charts/PDF/U1C90.pdf" &
wget "https://unicode.org/charts/PDF/U1CC0.pdf" &
wget "https://unicode.org/charts/PDF/U1CD0.pdf" &
wget "https://unicode.org/charts/PDF/U1D00.pdf" &
wget "https://unicode.org/charts/PDF/U1D000.pdf" &
wget "https://unicode.org/charts/PDF/U1D2E0.pdf" &
wget "https://unicode.org/charts/PDF/U1D80.pdf" &
wget "https://unicode.org/charts/PDF/U1D100.pdf" &
wget "https://unicode.org/charts/PDF/U1D200.pdf" &
wget "https://unicode.org/charts/PDF/U1D300.pdf" &
wget "https://unicode.org/charts/PDF/U1D360.pdf" &
wget "https://unicode.org/charts/PDF/U1D400.pdf" &
wget "https://unicode.org/charts/PDF/U1D800.pdf" &
wget "https://unicode.org/charts/PDF/U1DC0.pdf" &
wget "https://unicode.org/charts/PDF/U1E00.pdf" &
wget "https://unicode.org/charts/PDF/U1E000.pdf" &
wget "https://unicode.org/charts/PDF/U1E2C0.pdf" &
wget "https://unicode.org/charts/PDF/U1E100.pdf" &
wget "https://unicode.org/charts/PDF/U1E800.pdf" &
wget "https://unicode.org/charts/PDF/U1E900.pdf" &
wget "https://unicode.org/charts/PDF/U1EC70.pdf" &
wget "https://unicode.org/charts/PDF/U1ED00.pdf" &
wget "https://unicode.org/charts/PDF/U1EE00.pdf" &
wget "https://unicode.org/charts/PDF/U1F0A0.pdf" &
wget "https://unicode.org/charts/PDF/U1F00.pdf" &
wget "https://unicode.org/charts/PDF/U1F000.pdf" &
wget "https://unicode.org/charts/PDF/U1F030.pdf" &
wget "https://unicode.org/charts/PDF/U1F100.pdf" &
wget "https://unicode.org/charts/PDF/U1F200.pdf" &
wget "https://unicode.org/charts/PDF/U1F300.pdf" &
wget "https://unicode.org/charts/PDF/U1F600.pdf" &
wget "https://unicode.org/charts/PDF/U1F650.pdf" &
wget "https://unicode.org/charts/PDF/U1F680.pdf" &
wget "https://unicode.org/charts/PDF/U1F700.pdf" &
wget "https://unicode.org/charts/PDF/U1F780.pdf" &
wget "https://unicode.org/charts/PDF/U1F800.pdf" &
wget "https://unicode.org/charts/PDF/U1F900.pdf" &
wget "https://unicode.org/charts/PDF/U1FA00.pdf" &
wget "https://unicode.org/charts/PDF/U1FA70.pdf" &
wget "https://unicode.org/charts/PDF/U1FF80.pdf" &
wget "https://unicode.org/charts/PDF/U2A00.pdf" &
wget "https://unicode.org/charts/PDF/U2A700.pdf" &
wget "https://unicode.org/charts/PDF/U2B00.pdf" &
wget "https://unicode.org/charts/PDF/U2B740.pdf" &
wget "https://unicode.org/charts/PDF/U2B820.pdf" &
wget "https://unicode.org/charts/PDF/U2C00.pdf" &
wget "https://unicode.org/charts/PDF/U2C60.pdf" &
wget "https://unicode.org/charts/PDF/U2C80.pdf" &
wget "https://unicode.org/charts/PDF/U2CEB0.pdf" &
wget "https://unicode.org/charts/PDF/U2D00.pdf" &
wget "https://unicode.org/charts/PDF/U2D30.pdf" &
wget "https://unicode.org/charts/PDF/U2D80.pdf" &
wget "https://unicode.org/charts/PDF/U2DE0.pdf" &
wget "https://unicode.org/charts/PDF/U2E00.pdf" &
wget "https://unicode.org/charts/PDF/U2E80.pdf" &
wget "https://unicode.org/charts/PDF/U2F00.pdf" &
wget "https://unicode.org/charts/PDF/U2F800.pdf" &
wget "https://unicode.org/charts/PDF/U2FF0.pdf" &
wget "https://unicode.org/charts/PDF/U2FF80.pdf" &
wget "https://unicode.org/charts/PDF/U3FF80.pdf" &
wget "https://unicode.org/charts/PDF/U4DC0.pdf" &
wget "https://unicode.org/charts/PDF/U4E00.pdf" &
wget "https://unicode.org/charts/PDF/U4FF80.pdf" &
wget "https://unicode.org/charts/PDF/U5FF80.pdf" &
wget "https://unicode.org/charts/PDF/U6FF80.pdf" &
wget "https://unicode.org/charts/PDF/U7FF80.pdf" &
wget "https://unicode.org/charts/PDF/U8FF80.pdf" &
wget "https://unicode.org/charts/PDF/U9FF80.pdf" &
wget "https://unicode.org/charts/PDF/U10A0.pdf" &
wget "https://unicode.org/charts/PDF/U10A00.pdf" &
wget "https://unicode.org/charts/PDF/U10A60.pdf" &
wget "https://unicode.org/charts/PDF/U10A80.pdf" &
wget "https://unicode.org/charts/PDF/U10AC0.pdf" &
wget "https://unicode.org/charts/PDF/U10B00.pdf" &
wget "https://unicode.org/charts/PDF/U10B40.pdf" &
wget "https://unicode.org/charts/PDF/U10B60.pdf" &
wget "https://unicode.org/charts/PDF/U10B80.pdf" &
wget "https://unicode.org/charts/PDF/U10C00.pdf" &
wget "https://unicode.org/charts/PDF/U10C80.pdf" &
wget "https://unicode.org/charts/PDF/U10D00.pdf" &
wget "https://unicode.org/charts/PDF/U10E60.pdf" &
wget "https://unicode.org/charts/PDF/U10F00.pdf" &
wget "https://unicode.org/charts/PDF/U10F30.pdf" &
wget "https://unicode.org/charts/PDF/U10FE0.pdf" &
wget "https://unicode.org/charts/PDF/U10FF80.pdf" &
wget "https://unicode.org/charts/PDF/U11A00.pdf" &
wget "https://unicode.org/charts/PDF/U11A50.pdf" &
wget "https://unicode.org/charts/PDF/U11AC0.pdf" &
wget "https://unicode.org/charts/PDF/U11C00.pdf" &
wget "https://unicode.org/charts/PDF/U11C70.pdf" &
wget "https://unicode.org/charts/PDF/U11D00.pdf" &
wget "https://unicode.org/charts/PDF/U11D60.pdf" &
wget "https://unicode.org/charts/PDF/U11EE0.pdf" &
wget "https://unicode.org/charts/PDF/U11FC0.pdf" &
wget "https://unicode.org/charts/PDF/U13A0.pdf" &
wget "https://unicode.org/charts/PDF/U16A0.pdf" &
wget "https://unicode.org/charts/PDF/U16A40.pdf" &
wget "https://unicode.org/charts/PDF/U16AD0.pdf" &
wget "https://unicode.org/charts/PDF/U16B00.pdf" &
wget "https://unicode.org/charts/PDF/U16E40.pdf" &
wget "https://unicode.org/charts/PDF/U16F00.pdf" &
wget "https://unicode.org/charts/PDF/U16FE0.pdf" &
wget "https://unicode.org/charts/PDF/U18B0.pdf" &
wget "https://unicode.org/charts/PDF/U19E0.pdf" &
wget "https://unicode.org/charts/PDF/U20A0.pdf" &
wget "https://unicode.org/charts/PDF/U20D0.pdf" &
wget "https://unicode.org/charts/PDF/U25A0.pdf" &
wget "https://unicode.org/charts/PDF/U27C0.pdf" &
wget "https://unicode.org/charts/PDF/U27F0.pdf" &
wget "https://unicode.org/charts/PDF/U30A0.pdf" &
wget "https://unicode.org/charts/PDF/U31A0.pdf" &
wget "https://unicode.org/charts/PDF/U31C0.pdf" &
wget "https://unicode.org/charts/PDF/U31F0.pdf" &
wget "https://unicode.org/charts/PDF/U101D0.pdf" &
wget "https://unicode.org/charts/PDF/U102A0.pdf" &
wget "https://unicode.org/charts/PDF/U102E0.pdf" &
wget "https://unicode.org/charts/PDF/U103A0.pdf" &
wget "https://unicode.org/charts/PDF/U104B0.pdf" &
wget "https://unicode.org/charts/PDF/U108E0.pdf" &
wget "https://unicode.org/charts/PDF/U109A0.pdf" &
wget "https://unicode.org/charts/PDF/U110D0.pdf" &
wget "https://unicode.org/charts/PDF/U111E0.pdf" &
wget "https://unicode.org/charts/PDF/U112B0.pdf" &
wget "https://unicode.org/charts/PDF/U118A0.pdf" &
wget "https://unicode.org/charts/PDF/U119A0.pdf" &
wget "https://unicode.org/charts/PDF/U1000.pdf" &
wget "https://unicode.org/charts/PDF/U1100.pdf" &
wget "https://unicode.org/charts/PDF/U1200.pdf" &
wget "https://unicode.org/charts/PDF/U1380.pdf" &
wget "https://unicode.org/charts/PDF/U1400.pdf" &
wget "https://unicode.org/charts/PDF/U1680.pdf" &
wget "https://unicode.org/charts/PDF/U1700.pdf" &
wget "https://unicode.org/charts/PDF/U1720.pdf" &
wget "https://unicode.org/charts/PDF/U1740.pdf" &
wget "https://unicode.org/charts/PDF/U1760.pdf" &
wget "https://unicode.org/charts/PDF/U1780.pdf" &
wget "https://unicode.org/charts/PDF/U1800.pdf" &
wget "https://unicode.org/charts/PDF/U1900.pdf" &
wget "https://unicode.org/charts/PDF/U1950.pdf" &
wget "https://unicode.org/charts/PDF/U1980.pdf" &
wget "https://unicode.org/charts/PDF/U2000.pdf" &
wget "https://unicode.org/charts/PDF/U2070.pdf" &
wget "https://unicode.org/charts/PDF/U2100.pdf" &
wget "https://unicode.org/charts/PDF/U2150.pdf" &
wget "https://unicode.org/charts/PDF/U2190.pdf" &
wget "https://unicode.org/charts/PDF/U2200.pdf" &
wget "https://unicode.org/charts/PDF/U2300.pdf" &
wget "https://unicode.org/charts/PDF/U2400.pdf" &
wget "https://unicode.org/charts/PDF/U2440.pdf" &
wget "https://unicode.org/charts/PDF/U2460.pdf" &
wget "https://unicode.org/charts/PDF/U2500.pdf" &
wget "https://unicode.org/charts/PDF/U2580.pdf" &
wget "https://unicode.org/charts/PDF/U2600.pdf" &
wget "https://unicode.org/charts/PDF/U2700.pdf" &
wget "https://unicode.org/charts/PDF/U2800.pdf" &
wget "https://unicode.org/charts/PDF/U2900.pdf" &
wget "https://unicode.org/charts/PDF/U2980.pdf" &
wget "https://unicode.org/charts/PDF/U3000.pdf" &
wget "https://unicode.org/charts/PDF/U3040.pdf" &
wget "https://unicode.org/charts/PDF/U3100.pdf" &
wget "https://unicode.org/charts/PDF/U3130.pdf" &
wget "https://unicode.org/charts/PDF/U3190.pdf" &
wget "https://unicode.org/charts/PDF/U3200.pdf" &
wget "https://unicode.org/charts/PDF/U3300.pdf" &
wget "https://unicode.org/charts/PDF/U3400.pdf" &
wget "https://unicode.org/charts/PDF/U10000.pdf" &
wget "https://unicode.org/charts/PDF/U10080.pdf" &
wget "https://unicode.org/charts/PDF/U10100.pdf" &
wget "https://unicode.org/charts/PDF/U10140.pdf" &
wget "https://unicode.org/charts/PDF/U10190.pdf" &
wget "https://unicode.org/charts/PDF/U10280.pdf" &
wget "https://unicode.org/charts/PDF/U10300.pdf" &
wget "https://unicode.org/charts/PDF/U10330.pdf" &
wget "https://unicode.org/charts/PDF/U10350.pdf" &
wget "https://unicode.org/charts/PDF/U10380.pdf" &
wget "https://unicode.org/charts/PDF/U10400.pdf" &
wget "https://unicode.org/charts/PDF/U10450.pdf" &
wget "https://unicode.org/charts/PDF/U10480.pdf" &
wget "https://unicode.org/charts/PDF/U10500.pdf" &
wget "https://unicode.org/charts/PDF/U10530.pdf" &
wget "https://unicode.org/charts/PDF/U10600.pdf" &
wget "https://unicode.org/charts/PDF/U10800.pdf" &
wget "https://unicode.org/charts/PDF/U10840.pdf" &
wget "https://unicode.org/charts/PDF/U10860.pdf" &
wget "https://unicode.org/charts/PDF/U10880.pdf" &
wget "https://unicode.org/charts/PDF/U10900.pdf" &
wget "https://unicode.org/charts/PDF/U10920.pdf" &
wget "https://unicode.org/charts/PDF/U10980.pdf" &
wget "https://unicode.org/charts/PDF/U11000.pdf" &
wget "https://unicode.org/charts/PDF/U11080.pdf" &
wget "https://unicode.org/charts/PDF/U11100.pdf" &
wget "https://unicode.org/charts/PDF/U11150.pdf" &
wget "https://unicode.org/charts/PDF/U11180.pdf" &
wget "https://unicode.org/charts/PDF/U11200.pdf" &
wget "https://unicode.org/charts/PDF/U11280.pdf" &
wget "https://unicode.org/charts/PDF/U11300.pdf" &
wget "https://unicode.org/charts/PDF/U11400.pdf" &
wget "https://unicode.org/charts/PDF/U11480.pdf" &
wget "https://unicode.org/charts/PDF/U11580.pdf" &
wget "https://unicode.org/charts/PDF/U11600.pdf" &
wget "https://unicode.org/charts/PDF/U11660.pdf" &
wget "https://unicode.org/charts/PDF/U11680.pdf" &
wget "https://unicode.org/charts/PDF/U11700.pdf" &
wget "https://unicode.org/charts/PDF/U11800.pdf" &
wget "https://unicode.org/charts/PDF/U12000.pdf" &
wget "https://unicode.org/charts/PDF/U12400.pdf" &
wget "https://unicode.org/charts/PDF/U12480.pdf" &
wget "https://unicode.org/charts/PDF/U13000.pdf" &
wget "https://unicode.org/charts/PDF/U13430.pdf" &
wget "https://unicode.org/charts/PDF/U14400.pdf" &
wget "https://unicode.org/charts/PDF/U16800.pdf" &
wget "https://unicode.org/charts/PDF/U17000.pdf" &
wget "https://unicode.org/charts/PDF/U18800.pdf" &
wget "https://unicode.org/charts/PDF/U20000.pdf" &
wget "https://unicode.org/charts/PDF/U100000.pdf" &
wget "https://unicode.org/charts/PDF/UA000.pdf" &
wget "https://unicode.org/charts/PDF/UA4D0.pdf" &
wget "https://unicode.org/charts/PDF/UA6A0.pdf" &
wget "https://unicode.org/charts/PDF/UA8E0.pdf" &
wget "https://unicode.org/charts/PDF/UA9E0.pdf" &
wget "https://unicode.org/charts/PDF/UA490.pdf" &
wget "https://unicode.org/charts/PDF/UA500.pdf" &
wget "https://unicode.org/charts/PDF/UA640.pdf" &
wget "https://unicode.org/charts/PDF/UA700.pdf" &
wget "https://unicode.org/charts/PDF/UA720.pdf" &
wget "https://unicode.org/charts/PDF/UA800.pdf" &
wget "https://unicode.org/charts/PDF/UA830.pdf" &
wget "https://unicode.org/charts/PDF/UA840.pdf" &
wget "https://unicode.org/charts/PDF/UA880.pdf" &
wget "https://unicode.org/charts/PDF/UA900.pdf" &
wget "https://unicode.org/charts/PDF/UA930.pdf" &
wget "https://unicode.org/charts/PDF/UA960.pdf" &
wget "https://unicode.org/charts/PDF/UA980.pdf" &
wget "https://unicode.org/charts/PDF/UAA00.pdf" &
wget "https://unicode.org/charts/PDF/UAA60.pdf" &
wget "https://unicode.org/charts/PDF/UAA80.pdf" &
wget "https://unicode.org/charts/PDF/UAAE0.pdf" &
wget "https://unicode.org/charts/PDF/UAB00.pdf" &
wget "https://unicode.org/charts/PDF/UAB30.pdf" &
wget "https://unicode.org/charts/PDF/UAB70.pdf" &
wget "https://unicode.org/charts/PDF/UABC0.pdf" &
wget "https://unicode.org/charts/PDF/UAC00.pdf" &
wget "https://unicode.org/charts/PDF/UAFF80.pdf" &
wget "https://unicode.org/charts/PDF/UBFF80.pdf" &
wget "https://unicode.org/charts/PDF/UBOOP.pdf" &
wget "https://unicode.org/charts/PDF/UCFF80.pdf" &
wget "https://unicode.org/charts/PDF/UD7B0.pdf" &
wget "https://unicode.org/charts/PDF/UD800.pdf" &
wget "https://unicode.org/charts/PDF/UDC00.pdf" &
wget "https://unicode.org/charts/PDF/UDFF80.pdf" &
wget "https://unicode.org/charts/PDF/UE000.pdf" &
wget "https://unicode.org/charts/PDF/UE0000.pdf" &
wget "https://unicode.org/charts/PDF/UE0100.pdf" &
wget "https://unicode.org/charts/PDF/UEFF80.pdf" &
wget "https://unicode.org/charts/PDF/UF0000.pdf" &
wget "https://unicode.org/charts/PDF/UF900.pdf" &
wget "https://unicode.org/charts/PDF/UFB00.pdf" &
wget "https://unicode.org/charts/PDF/UFB50.pdf" &
wget "https://unicode.org/charts/PDF/UFE00.pdf" &
wget "https://unicode.org/charts/PDF/UFE10.pdf" &
wget "https://unicode.org/charts/PDF/UFE20.pdf" &
wget "https://unicode.org/charts/PDF/UFE30.pdf" &
wget "https://unicode.org/charts/PDF/UFE50.pdf" &
wget "https://unicode.org/charts/PDF/UFE70.pdf" &
wget "https://unicode.org/charts/PDF/UFF00.pdf" &
wget "https://unicode.org/charts/PDF/UFFF0.pdf" &
wget "https://unicode.org/charts/PDF/UFFF80.pdf" &
wget "https://unicode.org/charts/PDF/Z-U100000.pdf" &
wget "https://unicode.org/charts/PDF/Z-UD800.pdf" &
wget "https://unicode.org/charts/PDF/Z-UDC00.pdf" &
wget "https://unicode.org/charts/PDF/Z-UE000.pdf" &
wget "https://unicode.org/charts/PDF/Z-UF0000.pdf" &
