"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var main_1 = require("./main");
var file0 = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz";
console.log(main_1.gfe(file0, 6));
console.log(main_1.gfe(file0, 7));
console.log(main_1.gfe(file0, 8));
console.log(main_1.gfe(file0, 9));
console.log(main_1.gfe(file0, 11));
console.log(main_1.gfe(file0, 12));
console.log(main_1.gfe(file0, 13));
console.log(main_1.gfe(file0, 14));
console.log(main_1.gfe(file0, 15));
console.log(main_1.gfe(file0, 16));
