!/bin/bash
rg 
rg --no-trim
rg --no-json
rg --version
rg --unrestricted
rg --replace
rg --no-crlf
rg --heading
rg -g/--glob
rg --no-ignore-vcs
rg --ignore-file-case-insensitive
rg --no-multiline-dotall
rg -z/--search-zip
rg --context
rg --no-filename
rg -a/--text
rg --vimgrep
rg --no-mmap
rg --one-file-system
rg --threads
rg --case-sensitive
rg --type-not
rg --ignore-file
rg --ignore-vcs
rg -foo
rg --with-filename
rg --max-columns-preview
rg --max-depth
rg --pre-glob
rg --max-count
rg -H/--with-filename
rg --no-encoding
rg --no-line-number
rg --glob
rg --json
rg -cdq
rg --no-pcre2-unicode
rg --glob-case-insensitive
rg --null-data
rg --regex-size-limit
rg --help
rg --multiline
rg --null
rg --trace
rg --no-ignore-dot
rg --before-context
rg --print
rg --only-matching
rg --line-buffered
rg --pcre
rg -R'
rg --pre
rg --no-config
rg --follow
rg --pcre2-unicode
rg --debug
rg --dfa-size-limit
rg --no-hidden
rg --no-block-buffered
rg -o/--only-matching
rg --context-separator
rg --messages
rg --line-regexp
rg --word-regexp
rg --no-heading
rg -B/--before-context
rg --hidden
rg --path-separator
rg --type
rg --no-ignore
rg --no-ignore-global
rg -r'
rg --no-multiline
rg -U/--multiline
rg -i/--ignore-case
rg --multiline-dotall
rg --ignore-global
rg --encoding
rg --binary
rg --ignore-parent
rg --no-pcre2
rg --color
rg --ignore-messages
rg -g
rg -f
rg -e
rg -e/--regexp
rg -0/--null
rg --no-stats
rg -tfoo
rg --after-context
rg -o
rg -f/--file
rg --colors
rg --ignore
rg -h
rg -u
rg --no-search-zip
rg -p
rg --files-without-match
rg --no-line-buffered
rg -A/--after-context
rg --stats
rg --file
rg --pcre2-version
rg --ignore-dot
rg --line-number'
rg --type-clear
rg --invert-match
rg --no-glob-case-insensitive
rg --mmap
rg -s/--case-sensitive
rg --sortr
rg --files
rg --no-one-file-system
rg --no-follow
rg --auto-hybrid-regex
rg --type-add
rg --no-ignore-messages
rg --regexp
rg --no-column
rg --smart-case
rg --no-fixed-strings
rg --no-ignore-file-case-insensitive
rg --passthru
rg --no-ignore-parent
rg --text
rg --block-buffered
rg --count-matches
rg --pretty
rg --no-auto-hybrid-regex
rg --no-messages
rg -S/--smart-case
rg --files-with-matches
rg --byte-offset
rg --sort
rg --count
rg --max-filesize
rg -uuu
rg --quiet
rg --line-number
rg --crlf
rg --fixed-strings
rg --trim
rg -uuu'
rg --iglob
rg --column
rg --max-columns
rg --search-zip
rg --type-list
rg --ignore-case
